print("Welcome to the tip calculator!")
tip=int(input("What was the total bill? "))
perc=int(input("How much tip would you like to give? 10,12 or 15? "))
people=int(input("How many people to split the bill? "))
result=round((tip+(tip*perc/100))/people,2)
print(f"Each person should pay: ${result}")